# Generated by Django 5.2.13 on 2026-09-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_regiao_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='embedding',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('video', 'Vídeo'), ('checklist', 'Checklist'), ('link', 'Link')], default='text', max_length=20),
        ),
    ]
