# Generated by Django 5.2.13 on 2026-09-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contentblock_embedding_alter_contentblock_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='image_description',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
